controlServer/config/routes.rb
Rails.application.routes.draw do
  get 'hallucigif/show'
  get 'hallucigif/submit'

  get '/' => 'hallucigif#show'
  get '/submit' => 'hallucigif#submit'
  get 'render_gif' => 'hallucigif#render_gif', as: :render_gif

end

controlServer/app/models/hallucigif.rb
class Hallucigif < ActiveRecord::Base
    validates :link, presence: true, :format => URI::regexp(%w(http https))

end

controlServer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

controlServer/app/controllers/hallucigif_controller.rb
class HallucigifController < ApplicationController
  def index
  end

  def show
  end

  def render_gif
    puts "ayyyyyyy" + @url.to_s
    @job = Delayed::Job.enqueue RenderJob.new(url: @url, start: @start, duration: @duration)
  end
  
  def submit
    @ytlink = params[:link]
    @minute = params[:video_start]["from_time(5i)"]
    @second = params[:video_start]["from_time(6i)"]
    @gif_duration  = params[:duration]["duration_id"]
    @time = "00:" + @minute + ":" + @second
    @url = @ytlink
    @start = @time
    @duration = "00:00:0" + @gif_duration
    
    puts "ayye" + @url

    job = Hallucigif.new 
    job.link = @ytlink
    job.valid?
    if job.valid? != true
        flash[:message] = "Invalid link!" 
        redirect_to '/'
    end
    job.save
  end
end

controlServer/app/helpers/application_helper.rb
module ApplicationHelper
end

controlServer/app/helpers/hallucigif_helper.rb
module HallucigifHelper
end

controlServer/app/views/hallucigif/render_gif.js.haml
:plain
  var interval;
  $('.render .well').show();
  interval = setInterval(function(){
    $.ajax({
      url: '/progress-job/' + #{@job.id},
      success: function(job){
        var stage, progress;

        // If there are errors
        if (job.last_error != null) {
          $('.progress-status').addClass('text-danger').text(job.progress_stage);
          $('.progress-bar').addClass('progress-bar-danger');
          $('.progress').removeClass('active');
          clearInterval(interval);
        }

        progress = job.progress_current / job.progress_max * 100;
        // In job stage
        if (progress.toString() !== 'NaN'){
          $('.progress-status').text(job.progress_current + '/' + job.progress_max);
          $('.progress-bar').css('width', progress + '%').text(progress + '%');
        }
      },
      error: function(){
        // Job is no loger in database which means it finished successfuly
        $('.progress').removeClass('active');
        $('.progress-bar').css('width', '100%').text('100%');
        $('.progress-status').text('Successfully rendered!');
        $('.render-link').show();
        clearInterval(interval);
      }
    })
  },100);

controlServer/app/views/hallucigif/show.html.erb
<h1>Hallucigif</h1>
<% if flash[:message] %>
<p><%=flash[:message] %></p>
<% end %>
<%= form_tag("/submit", method: "get") do %>
  <%= label_tag(:link, "Youtube URL:") %>

  <%= text_field_tag(:link, nil, placeholder: "Enter URL...", :size=> 50) %>

  <br/>
  <%= label_tag(:video_start, "Start Time:") %>
  <%= time_select :video_start, :from_time, discard_hour: true, include_seconds: true, :default => {:minute => '00', :second => '00'} %>
  <br/>
  <%= label_tag(:duration, "Duration in seconds:") %>
  <%= select(:duration, :duration_id, [['1', 1], ['2', 2],['3', 3],['4', 4],['5', 5]]) %> 
  <br/>
  <%= submit_tag("Submit") %>
<% end %>

controlServer/app/views/hallucigif/submit.html.erb
<h1>Hallucigif</h1>
<h5>Job URL:</h5> <p> <%=@ytlink%> </p> 
<h5>Start Time:</h5>  <p> <%=@time%> </p> 
<h5>Duration:</h5>  <p>  <%=@gif_duration%> </p> 


<div class="render">
  <%= link_to 'Render GIF', render_gif_path, remote: true, class: 'btn btn-primary btn-lg' %>
  <div class="well">
    <div class="row">
      <div class="col-xs-12">
        <div class="progress-status text-primary">
          0/0
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <div class="progress progress-striped active">
          <div class="progress-bar">
            <div class="text-primary">
              0%
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= link_to 'View GIF', '/system/export.csv', class: 'btn btn-success render-link', style: 'display:none' %>
</div>

controlServer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ControlServer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>